### ISSUE TITLE
Dependencies dependencies = new Dependencies(

### ISSUE THREAD

**Issue by vitaly-chibrikov** [KhasanovBI/tp_2015_02_java_double_danger#14]
Dependencies dependencies = new Dependencies(
                null,
                DBAccountServiceImpl.instanciate(),
                ResourceServiceImpl.instanciate(),
                WebSocketServiceImpl.instanciate()
        );

убрать instatnciate() у всех этих сервисов. создавать сервисы через вызов конструктора напрямую.

**Comment by KhasanovBI** [comment]
А как же singleton?
